name: lando-go-1
services:
  defaults:
    type: go:1.19
    command: go run /app/http.go
  patch:
    type: go:1.24.3
  cli:
    type: go:1.19

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/go": ./../../
