name: lando-go-custom
services:
  custom:
    type: go
    ssl: true
    command: go run /app/https.go

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/go": ./../../